import { MapPin, MessageCircle, Navigation, Phone } from 'lucide-react';
import ContactForm from './ContactForm';
import { siteInfo } from '@/data/site';

export const metadata = { title: 'Contato | IBESC', description: 'Fale com o IBESC em Boa Viagem — CE e solicite informações sobre cursos e atendimento.' };
const whatsappUrl = `https://wa.me/${siteInfo.whatsapp}?text=${encodeURIComponent('Olá! Vim pelo site do IBESC e gostaria de receber informações sobre os cursos.')}`;

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Contato</span><h1>Fale com a equipe do IBESC</h1><p>Informe o curso ou a área que procura. Nossa equipe responderá com as orientações disponíveis para o atendimento.</p><div className="hero-actions"><a className="btn btn-primary" href={whatsappUrl}><MessageCircle size={17}/> Abrir WhatsApp</a><a className="btn btn-outline" href={siteInfo.googleMapsDirectionsUrl} target="_blank" rel="noopener noreferrer"><Navigation size={17}/> Como chegar</a></div></div></section>
  <section className="section"><div className="container contact-grid"><div><span className="eyebrow">Canais de atendimento</span><h2>Escolha como prefere conversar</h2><p>Para agilizar o atendimento, informe o nome do curso, a instituição ou a área de interesse.</p><div className="contact-cards"><article className="card"><MessageCircle/><h3>WhatsApp</h3><p>Solicite informações sobre cursos, disponibilidade, matrícula e suporte acadêmico.</p><a className="link" href={whatsappUrl}>Iniciar conversa</a></article><article className="card"><Phone/><h3>Telefone</h3><p>{siteInfo.phone}</p><a className="link" href={`tel:${siteInfo.phone.replace(/\s/g,'')}`}>Ligar agora</a></article><article className="card"><MapPin/><h3>Endereço</h3><p>{siteInfo.streetAddress}<br/>{siteInfo.neighborhood}<br/>{siteInfo.city} — {siteInfo.state}<br/>{siteInfo.postalCode}</p><a className="link" href={siteInfo.googleMapsDirectionsUrl} target="_blank" rel="noopener noreferrer">Abrir rota</a></article></div></div><div><div className="section-head compact-head"><span className="eyebrow">Formulário</span><h2>Envie sua solicitação</h2><p>Se preferir, deixe seus dados e descreva o que procura.</p></div><ContactForm/></div></div></section></main>;
}
