import Link from 'next/link';
import { Building2, GraduationCap, MapPin, MessagesSquare, ArrowRight } from 'lucide-react';
import { siteInfo } from '@/data/site';

export const metadata = { title: 'Sobre o IBESC | Instituto Brasileiro de Educação, Saúde e Cultura', description: 'Conheça a atuação do IBESC em Boa Viagem, seus cursos próprios e o atendimento relacionado a instituições parceiras.' };

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Sobre o IBESC</span><h1>Formação e orientação educacional em Boa Viagem</h1><p>O IBESC reúne cursos próprios, atendimento e suporte acadêmico para todas as formações apresentadas no site, com clareza sobre o papel de cada instituição.</p></div></section>
  <section className="section"><div className="container contact-grid"><div><span className="eyebrow">Quem somos</span><h2>Instituto Brasileiro de Educação, Saúde e Cultura</h2><p>O IBESC atua em Boa Viagem — CE com cursos próprios e atendimento para pessoas que procuram diferentes caminhos de formação.</p><p>A equipe IBESC presta suporte acadêmico e atendimento em todos os cursos. Nas ofertas parceiras, a instituição indicada permanece responsável pela oferta, pelas regras acadêmicas e pela certificação.</p></div><aside className="card institutional-address"><MapPin/><h3>Atuação local</h3><p>{siteInfo.streetAddress}<br/>{siteInfo.neighborhood}<br/>{siteInfo.city} — {siteInfo.state}<br/>{siteInfo.postalCode}</p><a className="link" href={siteInfo.googleMapsDirectionsUrl} target="_blank" rel="noopener noreferrer">Como chegar <ArrowRight size={15}/></a></aside></div></section>
  <section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Como atuamos</span><h2>Responsabilidades apresentadas com clareza</h2></div><div className="path-grid"><div className="card"><GraduationCap/><h3>Formações próprias</h3><p>Cursos identificados como IBESC apresentam as informações correspondentes à oferta do instituto.</p></div><div className="card"><Building2/><h3>Instituições parceiras</h3><p>UNINASSAU e UNIFAEL respondem academicamente pelas formações identificadas com suas marcas.</p></div><div className="card"><MessagesSquare/><h3>Suporte acadêmico</h3><p>A equipe ajuda o interessado a localizar opções e entender o canal adequado para avançar.</p></div></div></div></section>
  <section className="section"><div className="container"><div className="cta"><div><span className="eyebrow">Conheça de perto</span><h2>Veja a estrutura ou fale com a equipe</h2><p>Conheça os ambientes reais do IBESC e os canais de atendimento em Boa Viagem.</p></div><div className="hero-actions"><Link className="btn btn-dark" href="/estrutura">Conhecer a estrutura</Link><Link className="btn btn-primary" href="/contato">Entrar em contato</Link></div></div></div></section></main>;
}
