import Link from 'next/link';
import Image from 'next/image';
import { Building2, GraduationCap, MapPin, MessagesSquare, ArrowRight } from 'lucide-react';
import { siteInfo } from '@/data/site';

export const metadata = { title: 'Sobre o IBESC | Instituto Brasileiro de Educação, Saúde e Cultura', description: 'Conheça a atuação do IBESC em Boa Viagem, seus cursos próprios e o atendimento relacionado a instituições parceiras.' };

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Sobre o IBESC</span><h1>Formação e orientação educacional em Boa Viagem</h1><p>O IBESC reúne cursos próprios, atendimento e suporte acadêmico para todas as formações apresentadas no site, com clareza sobre o papel de cada instituição.</p></div></section>
  <section className="section about-history-section"><div className="container about-history-grid"><figure className="about-founder-photo"><Image src="/images/professor-sandoval-vieira.webp" alt="Professor Sandoval Vieira, idealizador e fundador do IBESC" width={854} height={1250} priority sizes="(max-width: 800px) 100vw, 42vw"/><figcaption><strong>Professor Sandoval Vieira</strong><span>Idealizador e fundador do IBESC</span></figcaption></figure><div className="about-history-copy"><span className="eyebrow">Nossa história</span><h2>Instituto Brasileiro de Educação, Saúde e Cultura</h2><p>O IBESC nasceu do sonho de um jovem professor que encontrou na educação a oportunidade de empreender e contribuir para a transformação social.</p><p>Idealizado e fundado pelo <strong className="founder-name">Professor Sandoval Vieira</strong>, o Instituto foi concebido com o propósito de ampliar o acesso ao conhecimento e oferecer diferentes possibilidades de formação. Sua atuação é desenvolvida por meio de cursos próprios e de parcerias com instituições de ensino reconhecidas e credenciadas pelos órgãos competentes, sempre com clareza quanto às responsabilidades acadêmicas de cada instituição.</p><p>A criação do IBESC foi marcada pela iniciativa, pela perseverança diante dos desafios e pela convicção de que a educação constitui um dos principais instrumentos de desenvolvimento humano e profissional. Para o <strong className="founder-name">Professor Sandoval Vieira</strong>, o conhecimento possui o poder de transformar trajetórias, ampliar oportunidades e contribuir para mudanças significativas na realidade das pessoas e das comunidades.</p><p>Com visão empreendedora, compromisso social e dedicação ao ensino, o IBESC vem construindo sua história com base em valores como ética, responsabilidade, respeito, inclusão, valorização do conhecimento e busca permanente pela qualidade educacional.</p><p>Mais do que oferecer oportunidades de formação, o IBESC procura acolher, orientar e apoiar cada estudante em sua trajetória, contribuindo para que novos projetos profissionais e pessoais possam ser construídos por meio da educação.</p><aside className="about-address"><MapPin/><div><strong>Atuação local</strong><span>{siteInfo.streetAddress}, {siteInfo.neighborhood}<br/>{siteInfo.city} — {siteInfo.state} · {siteInfo.postalCode}</span><a className="link" href={siteInfo.googleMapsDirectionsUrl} target="_blank" rel="noopener noreferrer">Como chegar <ArrowRight size={15}/></a></div></aside></div></div></section>
  <section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Como atuamos</span><h2>Responsabilidades apresentadas com clareza</h2></div><div className="path-grid"><div className="card"><GraduationCap/><h3>Formações próprias</h3><p>Cursos identificados como IBESC apresentam as informações correspondentes à oferta do instituto.</p></div><div className="card"><Building2/><h3>Instituições parceiras</h3><p>UNINASSAU e UNIFAEL respondem academicamente pelas formações identificadas com suas marcas.</p></div><div className="card"><MessagesSquare/><h3>Suporte acadêmico</h3><p>A equipe ajuda o interessado a localizar opções e entender o canal adequado para avançar.</p></div></div></div></section>
  <section className="section"><div className="container"><div className="cta"><div><span className="eyebrow">Conheça de perto</span><h2>Veja a estrutura ou fale com a equipe</h2><p>Conheça os ambientes reais do IBESC e os canais de atendimento em Boa Viagem.</p></div><div className="hero-actions"><Link className="btn btn-dark" href="/estrutura">Conhecer a estrutura</Link><Link className="btn btn-primary" href="/contato">Entrar em contato</Link></div></div></div></section></main>;
}
