import Link from 'next/link';
import { ExternalLink, MessageCircle, ArrowRight, Building2, GraduationCap, MessagesSquare } from 'lucide-react';

export const metadata = { title: 'Graduação UNINASSAU | Orientação IBESC', description: 'Consulte o catálogo oficial de graduação da UNINASSAU e receba orientação comercial do IBESC em Boa Viagem.' };
const catalogUrl = 'https://graduacao.uninassau.digital/nossos-cursos';
const whatsapp = 'https://wa.me/5588988498031?text=' + encodeURIComponent('Olá! Vim pelo site do IBESC e quero informações sobre as graduações da UNINASSAU.');
const faqs = [
  ['Quem é responsável pela graduação?', 'A formação acadêmica e as regras do curso são de responsabilidade da UNINASSAU. O IBESC oferece orientação comercial e atendimento em Boa Viagem.'],
  ['Onde encontro as informações oficiais?', 'Cursos, modalidades, condições acadêmicas e regras de ingresso devem ser consultados no catálogo e nos canais oficiais da UNINASSAU.'],
  ['Como o IBESC pode ajudar?', 'A equipe pode orientar sua busca, esclarecer o fluxo comercial disponível e indicar o canal correspondente para avançar.'],
];

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Graduação · UNINASSAU</span><h1>Escolha sua graduação com informações claras</h1><p>Explore o catálogo oficial da UNINASSAU e conte com o atendimento comercial do IBESC em Boa Viagem durante sua escolha.</p><div className="hero-actions"><a className="btn btn-primary" href={catalogUrl} target="_blank" rel="noopener noreferrer">Ver catálogo oficial <ExternalLink size={17}/></a><a className="btn btn-outline" href={whatsapp}>Falar com o IBESC <MessageCircle size={17}/></a></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Responsabilidades claras</span><h2>Formação UNINASSAU, orientação comercial IBESC</h2><p>Você consulta a oferta acadêmica na fonte oficial e pode procurar o IBESC para receber orientação sobre as opções e o encaminhamento comercial disponível.</p></div><div className="path-grid"><div className="card"><GraduationCap/><h3>Responsabilidade acadêmica</h3><p>A UNINASSAU mantém o catálogo, a oferta, as regras acadêmicas e a formação.</p></div><div className="card"><MessagesSquare/><h3>Atendimento IBESC</h3><p>O IBESC ajuda a compreender as opções e orienta os próximos passos do atendimento.</p></div><div className="card"><Building2/><h3>Fonte oficial</h3><p>Modalidade, ingresso e condições atuais devem ser confirmados nos canais da instituição responsável.</p></div></div></div></section>
  <section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Como avançar</span><h2>Da pesquisa à orientação</h2></div><div className="steps">{[['01','Explore o catálogo','Consulte cursos e áreas diretamente na plataforma oficial.'],['02','Selecione suas opções','Anote os cursos que correspondem ao que você procura.'],['03','Converse com o IBESC','Tire dúvidas sobre o atendimento comercial disponível.'],['04','Siga o canal oficial','Confirme as informações e avance conforme as regras da instituição.']].map((item)=><div className="card step-card" key={item[0]}><div className="step-num">{item[0]}</div><h3>{item[1]}</h3><p>{item[2]}</p></div>)}</div></div></section>
  <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Dúvidas frequentes</span><h2>Antes de escolher sua graduação</h2></div><div className="faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div><div className="cta" style={{marginTop:40}}><div><h2>Quer ajuda para organizar suas opções?</h2><p>Fale com a equipe do IBESC ou acesse diretamente o catálogo acadêmico oficial.</p></div><div className="hero-actions"><a href={whatsapp} className="btn btn-dark">Falar no WhatsApp <MessageCircle size={17}/></a><a href={catalogUrl} target="_blank" rel="noopener noreferrer" className="btn btn-primary">Catálogo oficial <ExternalLink size={16}/></a></div></div></div></section>
  <div className="container" style={{paddingBottom:70}}><Link href="/cursos" className="link">Ver todos os cursos <ArrowRight size={15}/></Link></div></main>;
}
