import Link from 'next/link';
import { ExternalLink, MessageCircle, ArrowRight } from 'lucide-react';

export const metadata = { title: 'Graduação | IBESC', description: 'Encontre sua graduação por meio do IBESC e consulte o catálogo oficial da UNINASSAU.' };
const catalogUrl = 'https://graduacao.uninassau.digital/nossos-cursos';
const whatsapp = 'https://wa.me/5588988498031?text=' + encodeURIComponent('Olá! Vim pelo site do IBESC e quero informações sobre as graduações da UNINASSAU.');

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Graduação · UNINASSAU</span><h1>Encontre sua graduação</h1><p>Escolha uma formação que acompanhe seus objetivos profissionais. O IBESC orienta você e conecta você ao catálogo oficial da UNINASSAU.</p><div className="hero-actions"><a className="btn btn-primary" href={catalogUrl} target="_blank" rel="noopener noreferrer">Ver catálogo oficial <ExternalLink size={17}/></a><a className="btn btn-outline" href={whatsapp}>Falar com um consultor <MessageCircle size={17}/></a></div></div></section><section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Como funciona</span><h2>Escolha com orientação</h2><p>O catálogo de graduação é mantido pela UNINASSAU. Para evitar informações desatualizadas, o IBESC direciona você para a fonte oficial.</p></div><div className="path-grid"><div className="card"><strong>01</strong><h3>Explore os cursos</h3><p>Consulte as opções disponíveis diretamente no catálogo oficial.</p></div><div className="card"><strong>02</strong><h3>Fale com o IBESC</h3><p>Nossa equipe pode ajudar você a entender as opções e o processo comercial.</p></div><div className="card"><strong>03</strong><h3>Avance para a matrícula</h3><p>Após escolher sua formação, siga as orientações oficiais da instituição.</p></div></div><div className="cta" style={{marginTop:40}}><h2>Quer ajuda para escolher?</h2><p>Fale com um consultor do IBESC antes de avançar.</p><a href={whatsapp} className="btn btn-dark">Falar no WhatsApp <MessageCircle size={17}/></a></div></div></section><div className="container" style={{paddingBottom:70}}><Link href="/" className="link">← Voltar para o início <ArrowRight size={15}/></Link></div></main>;
}