import Link from 'next/link';
import { courses } from '@/data/courses';
import { ArrowRight, MessageCircle, Monitor, ShieldCheck } from 'lucide-react';

export const metadata={title:'Cursos Técnicos | IBESC',description:'Conheça os cursos técnicos próprios do IBESC em Boa Viagem — CE.'};
const wa='5588988498031';
const waLink=(name:string)=>`https://wa.me/${wa}?text=${encodeURIComponent(`Olá! Vim pelo site do IBESC e gostaria de receber informações sobre o curso de ${name}.`)}`;

export default function Page(){const list=courses.filter(c=>c.category==='TECNICO');return <main>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow" style={{background:'rgba(255,255,255,.12)',color:'#fff'}}>Formação própria IBESC</span><h1>Formação prática para novas oportunidades.</h1><p>Conheça os cursos técnicos do IBESC e converse com nossa equipe sobre a formação que combina com seus objetivos.</p><div className="hero-actions"><a className="btn btn-primary" href={`https://wa.me/${wa}?text=${encodeURIComponent('Olá! Vim pelo site do IBESC e quero conhecer os cursos técnicos.')}`}>Falar com um consultor</a></div></div><div className="hero-card"><div className="fake-photo"/><strong>Formação prática. Orientação próxima.</strong></div></div></section>
<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Cursos próprios</span><h2>Escolha seu próximo passo</h2><p>As informações acadêmicas e comerciais de cada turma são confirmadas pela equipe IBESC antes da matrícula.</p></div><div className="course-grid">{list.map(c=><article className="card course-card" key={c.id}>{c.image ? <img className="course-image course-image-element" src={c.image} alt={c.name} loading="lazy" /> : <div className="course-image course-image-placeholder" aria-hidden="true"><Monitor size={48}/></div>}<span className="tag">{c.type} • IBESC</span><h3>{c.name}</h3><div className="course-meta">Boa Viagem — CE • {c.area}</div><p>{c.description}</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="btn btn-dark" href={`/curso/${c.slug}`}>Saiba mais <ArrowRight size={16}/></Link><a className="btn btn-primary" href={waLink(c.name)}><MessageCircle size={16}/> WhatsApp</a></div></article>)}</div></div></section>
<section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Transparência</span><h2>Informação clara antes da matrícula</h2><p>Não apresentamos preços, duração, datas, horários ou número de vagas sem cadastro e confirmação. Nosso consultor orienta você com os dados disponíveis para a turma.</p></div><div className="diff-grid">{['Orientação para sua escolha','Atendimento próximo','Informações confirmadas','Próximos passos claros'].map(x=><div className="card" key={x}><ShieldCheck color="var(--green)"/><h3>{x}</h3><p>Converse com a equipe IBESC para receber as informações atuais do curso.</p></div>)}</div></div></section>
</main>}
