import Link from 'next/link';
import { ArrowRight, MapPin, Search, MessageCircle, CheckCircle2, GraduationCap, Stethoscope, Monitor, Building2 } from 'lucide-react';
import { courses, areas } from '@/data/courses';

const wa = '5588988498031';
const waLink = (course?: string) => `https://wa.me/${wa}?text=${encodeURIComponent(course ? `Olá! Vim pelo site do IBESC e gostaria de receber informações sobre o curso de ${course}.` : 'Olá! Vim pelo site do IBESC e gostaria de receber informações sobre os cursos.')}`;

function Header(){return <header className="header"><div className="container nav"><Link href="/" className="brand"><span className="brand-mark">IB</span><span><strong>IBESC</strong><small>Instituto Brasileiro de Educação, Saúde e Cultura</small></span></Link><nav className="nav-links"><Link href="/graduacao">Graduação</Link><Link href="/pos-graduacao">Pós-graduação</Link><Link href="/cursos-tecnicos">Cursos Técnicos</Link><Link href="/sobre">Sobre o IBESC</Link><Link href="/estrutura">Estrutura</Link><Link href="/contato">Contato</Link><Link href="/cursos" className="btn btn-dark">Encontre seu curso</Link></nav><button className="mobile-menu" aria-label="Abrir menu">☰</button></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><div className="brand"><span className="brand-mark">IB</span><span><strong style={{color:'white'}}>IBESC</strong><small>Instituto Brasileiro de Educação, Saúde e Cultura</small></span></div><p>Sua formação. Seu próximo passo.</p></div><div><h4>Formações</h4><Link href="/graduacao">Graduação</Link><Link href="/pos-graduacao">Pós-graduação</Link><Link href="/cursos-tecnicos">Cursos Técnicos</Link><Link href="/cursos">Cursos Profissionalizantes</Link></div><div><h4>Institucional</h4><Link href="/sobre">Sobre o IBESC</Link><Link href="/estrutura">Estrutura</Link><Link href="/contato">Contato</Link></div><div><h4>Atendimento</h4><p>Boa Viagem — CE</p><p>(88) 98849-8031</p><p>Parceiros: UNINASSAU e UNIFAEL</p></div></div><div className="container footer-bottom">© 2026 IBESC. Todos os direitos reservados.</div></footer>}

export default function Home(){const featured=courses.filter(c=>c.featured);return <><Header/><main>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow" style={{background:'rgba(255,255,255,.12)',color:'#fff'}}>Boa Viagem — CE</span><h1>Sua próxima conquista começa com uma escolha.</h1><p>Encontre a formação ideal para transformar seus objetivos em novas oportunidades profissionais.</p><div className="hero-actions"><Link href="/cursos" className="btn btn-primary">Encontre seu curso <ArrowRight size={17}/></Link><a href={waLink()} className="btn btn-outline">Falar com um consultor</a></div><div className="location">Graduação • Pós-graduação • Cursos Técnicos</div></div><div className="hero-card"><div className="fake-photo"/><strong>Educação que aproxima você do seu próximo objetivo.</strong></div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Escolha seu caminho</span><h2>Qual caminho combina com você?</h2><p>Encontre a formação que faz sentido para o seu momento profissional.</p></div><div className="path-grid"><div className="card path-card"><GraduationCap size={34} color="var(--blue)"/><div><h3>Graduação</h3><p>Comece sua formação superior e construa uma carreira com novas possibilidades.</p></div><Link className="link" href="/graduacao">Ver graduações →</Link></div><div className="card path-card"><Building2 size={34} color="var(--green)"/><div><h3>Pós-graduação</h3><p>Especialize-se, atualize seus conhecimentos e avance profissionalmente.</p></div><Link className="link" href="/pos-graduacao">Ver pós-graduações →</Link></div><div className="card path-card"><Stethoscope size={34} color="var(--yellow)"/><div><h3>Cursos Técnicos</h3><p>Formação prática para quem quer se preparar para o mercado de trabalho.</p></div><Link className="link" href="/cursos-tecnicos">Ver cursos técnicos →</Link></div></div></div></section>

<section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Busca inteligente</span><h2>Encontre o curso ideal para você</h2></div><div className="search-box"><div className="search-grid"><input className="input" placeholder="Digite o nome do curso"/><select className="input"><option>Área: Todas</option></select><select className="input"><option>Formação: Todas</option></select><select className="input"><option>Instituição: Todas</option></select><Link className="btn btn-primary" href="/cursos"><Search size={17}/> Buscar</Link></div></div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Áreas de formação</span><h2>Explore nossas áreas</h2></div><div className="area-grid">{areas.map((area,i)=><Link href={`/cursos?area=${encodeURIComponent(area)}`} className="area-card" key={area}>{area}<span>Explorar cursos →</span></Link>)}</div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Cursos em destaque</span><h2>Cursos que podem transformar sua carreira</h2></div><div className="course-grid">{featured.map(c=><article className="card course-card" key={c.id}><div className="course-image"/><span className="tag">{c.type}</span><h3>{c.name}</h3><div className="course-meta">{Array.isArray(c.institution)?c.institution.join(' / '):c.institution} • {c.area}</div><p>{c.description}</p><Link className="link" href={`/curso/${c.slug}`}>Saiba mais →</Link></article>)}</div></div></section>

<section className="section dark-section"><div className="container"><div className="section-head"><span className="eyebrow" style={{background:'rgba(255,255,255,.1)',color:'#fff'}}>Por que IBESC?</span><h2>Mais do que um curso. Um caminho para o seu futuro.</h2><p>No IBESC, você encontra diferentes caminhos de formação em um só lugar.</p></div><div className="diff-grid">{[['01','Orientação para sua escolha','Você não precisa escolher sozinho. Nossa equipe ajuda você a encontrar a formação adequada aos seus objetivos.'],['02','Diversidade de formações','Graduação, pós-graduação e cursos técnicos em diferentes áreas.'],['03','Instituições parceiras','Opções de formação em parceria com instituições como UNINASSAU e UNIFAEL.'],['04','Atendimento próximo','Atendimento presencial em Boa Viagem e suporte durante sua jornada.']].map(d=><div className="card diff-card" key={d[0]}><span className="number">{d[0]}</span><h3>{d[1]}</h3><p>{d[2]}</p></div>)}</div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Formação prática</span><h2>Quer entrar no mercado mais rápido?</h2><p>Conheça os cursos técnicos do IBESC e prepare-se para novas oportunidades profissionais.</p></div><div className="tech-grid"><div className="card"><Stethoscope size={34} color="var(--green)"/><h3>Técnico em Enfermagem</h3><p>Prepare-se para construir uma carreira na área da saúde com formação técnica e prática.</p><a className="btn btn-dark" href={waLink('Técnico em Enfermagem')}>Quero saber mais</a></div><div className="card"><Monitor size={34} color="var(--blue)"/><h3>Técnico em Informática</h3><p>Desenvolva conhecimentos técnicos para atuar com tecnologia, suporte e informática.</p><a className="btn btn-dark" href={waLink('Técnico em Informática')}>Quero saber mais</a></div></div></div></section>

<section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Instituições parceiras</span><h2>Grandes instituições. Novos caminhos para você.</h2><p>O IBESC atua na comercialização e orientação de cursos oferecidos em parceria com instituições de ensino.</p></div><div className="partner-grid"><div className="partner">UNINASSAU</div><div className="partner">UNIFAEL</div></div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Como funciona</span><h2>Começar é mais simples do que você imagina</h2></div><div className="steps">{[['01','Escolha seu objetivo','Conte para nós o que você quer estudar.'],['02','Encontre seu curso','Nossa equipe apresenta as opções disponíveis para o seu perfil.'],['03','Faça sua matrícula','Receba orientação durante o processo de inscrição.'],['04','Comece sua formação','Agora é só dar o primeiro passo rumo ao seu próximo objetivo.']].map(s=><div className="card" key={s[0]}><div className="step-num">{s[0]}</div><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></div></section>

<section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Avaliação Google</span><h2>Quem estuda com a gente, recomenda.</h2></div><div className="testimonial"><div className="stars">★★★★★</div><h3>5,0 no Google</h3><p><strong>16 avaliações</strong></p><p>“Muito satisfatório, estrutura ampla com laboratório e pessoas especializadas.”</p><p>“Excelente instituição de ensino.”</p><span className="link">Ver avaliações →</span></div></div></section>

<section className="section"><div className="container"><div className="cta"><div className="section-head"><span className="eyebrow">Atendimento em Boa Viagem</span><h2>Não sabe qual curso escolher?</h2><p>Fale com um de nossos consultores e descubra quais opções combinam com seus objetivos profissionais.</p></div><a href={waLink()} className="btn btn-dark">Falar com um consultor</a></div></div></section>

<section className="section dark-section"><div className="container"><div className="cta" style={{background:'rgba(255,255,255,.08)'}}><div className="section-head"><h2>O seu próximo passo pode começar hoje.</h2><p>Escolha sua formação, fale com nossa equipe e descubra as opções disponíveis para você.</p></div><div className="hero-actions"><Link href="/cursos" className="btn btn-primary">Encontre seu curso</Link><a href={waLink()} className="btn btn-outline">Falar no WhatsApp</a></div></div></div></section>
</main><Footer/><a className="whatsapp" href={waLink()} aria-label="Fale com um consultor no WhatsApp"><MessageCircle size={18}/> Fale com um consultor</a></>}
