import Link from 'next/link';
import { ArrowRight, MessageCircle, GraduationCap, Stethoscope, Building2, CheckCircle2, MapPin } from 'lucide-react';
import { courses, areas } from '@/data/courses';

const wa = '5588988498031';
const waLink = (course?: string) => `https://wa.me/${wa}?text=${encodeURIComponent(course ? `Olá! Vim pelo site do IBESC e gostaria de receber informações sobre o curso de ${course}.` : 'Olá! Vim pelo site do IBESC e gostaria de receber informações sobre os cursos.')}`;

function Header(){return <header className="header"><div className="container nav"><Link href="/" className="brand" aria-label="IBESC - início"><img className="brand-logo" src="/images/LOGO OFICIAL.jpeg" alt="IBESC - Instituto Brasileiro de Educação, Saúde e Cultura"/><span className="sr-only">IBESC</span></Link><nav className="nav-links" aria-label="Navegação principal"><Link href="/graduacao">Graduação</Link><Link href="/pos-graduacao">Pós-graduação</Link><Link href="/cursos-tecnicos">Cursos Técnicos</Link><Link href="/sobre">Sobre</Link><Link href="/estrutura">Estrutura</Link><Link href="/contato">Contato</Link><Link href="/cursos" className="btn btn-dark">Encontre seu curso</Link></nav><button className="mobile-menu" aria-label="Abrir menu">☰</button></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><img className="footer-logo" src="/images/LOGO 2.jpeg" alt="IBESC"/><p>Sua formação. Seu próximo passo.</p></div><div><h4>Formações</h4><Link href="/graduacao">Graduação</Link><Link href="/pos-graduacao">Pós-graduação</Link><Link href="/cursos-tecnicos">Cursos Técnicos</Link><Link href="/cursos">Todos os cursos</Link></div><div><h4>Institucional</h4><Link href="/sobre">Sobre o IBESC</Link><Link href="/estrutura">Estrutura</Link><Link href="/contato">Contato</Link></div><div><h4>Atendimento</h4><p>Boa Viagem — CE</p><p>(88) 98849-8031</p><p>Parceiros: UNINASSAU e UNIFAEL</p><img className="footer-partner-logo" src="/images/LOGO 3.jpeg" alt="IBESC"/></div></div><div className="container footer-bottom">© 2026 IBESC. Todos os direitos reservados.</div></footer>}

export default function Home(){const featured=courses.filter(c=>c.featured);return <><Header/><main>
<section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow eyebrow-light"><MapPin size={14}/> Boa Viagem — CE</span><h1>Sua próxima conquista <span>começa com uma escolha.</span></h1><p>Encontre a formação ideal para transformar seus objetivos em novas oportunidades profissionais.</p><div className="hero-actions"><Link href="/cursos" className="btn btn-primary">Encontre seu curso <ArrowRight size={17}/></Link><a href={waLink()} className="btn btn-outline">Falar com um consultor</a></div><div className="hero-trust"><span>Graduação</span><i/> <span>Pós-graduação</span><i/> <span>Cursos Técnicos</span></div></div><div className="hero-visual"><div className="hero-photo"><img src="/images/LOGO 3.jpeg" alt="IBESC - formação e educação" fetchPriority="high"/></div><div className="hero-badge"><strong>Seu próximo passo</strong><span>começa aqui.</span></div><div className="hero-orbit"/></div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Escolha seu caminho</span><h2>Qual caminho combina com você?</h2><p>Encontre a formação que faz sentido para o seu momento profissional.</p></div><div className="path-grid"><Link href="/graduacao" className="card path-card"><div className="icon-wrap blue"><GraduationCap size={25}/></div><div><h3>Graduação</h3><p>Comece sua formação superior e construa uma carreira com novas possibilidades.</p></div><span className="link">Ver graduações <ArrowRight size={15}/></span></Link><Link href="/pos-graduacao" className="card path-card"><div className="icon-wrap green"><Building2 size={25}/></div><div><h3>Pós-graduação</h3><p>Especialize-se, atualize seus conhecimentos e avance profissionalmente.</p></div><span className="link">Ver pós-graduações <ArrowRight size={15}/></span></Link><Link href="/cursos-tecnicos" className="card path-card"><div className="icon-wrap yellow"><Stethoscope size={25}/></div><div><h3>Cursos Técnicos</h3><p>Formação prática para quem quer se preparar para o mercado de trabalho.</p></div><span className="link">Ver cursos técnicos <ArrowRight size={15}/></span></Link></div></div></section>

<section className="section search-section"><div className="container"><div className="section-head centered"><span className="eyebrow">Busca inteligente</span><h2>Encontre o curso ideal para você</h2><p>Pesquise por formação, área ou instituição e encontre seu próximo caminho.</p></div><div className="search-box"><div className="search-grid"><input className="input" placeholder="Digite o nome do curso" aria-label="Nome do curso"/><select className="input" aria-label="Área"><option>Área: Todas</option></select><select className="input" aria-label="Formação"><option>Formação: Todas</option></select><select className="input" aria-label="Instituição"><option>Instituição: Todas</option></select><Link className="btn btn-primary" href="/cursos">Buscar <ArrowRight size={16}/></Link></div></div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Áreas de formação</span><h2>Explore nossas áreas</h2></div><div className="area-grid">{areas.map(area=><Link href={`/cursos?area=${encodeURIComponent(area)}`} className="area-card" key={area}><span className="area-dot"/>{area}<small>Explorar cursos <ArrowRight size={13}/></small></Link>)}</div></div></section>

<section className="section featured-section"><div className="container"><div className="section-head row-head"><div><span className="eyebrow">Cursos em destaque</span><h2>Cursos que podem transformar sua carreira</h2></div><Link href="/cursos" className="link desktop-link">Ver todos os cursos <ArrowRight size={15}/></Link></div><div className="course-grid">{featured.map((c,i)=><article className="card course-card" key={c.id}><div className="course-image image-real"><img src={c.name.toLowerCase().includes('enfermagem')?'/images/tecnico-enfermagem-1.png':i===0?'/images/LOGO 3.jpeg':i===1?'/images/LOGO 2.jpeg':'/images/LOGO OFICIAL.jpeg'} alt={c.name} loading="lazy"/></div><span className="tag">{c.type}</span><h3>{c.name}</h3><div className="course-meta">{Array.isArray(c.institution)?c.institution.join(' / '):c.institution} <span/> {c.area}</div><p>{c.description}</p><Link className="link" href={`/curso/${c.slug}`}>Saiba mais <ArrowRight size={15}/></Link></article>)}</div></div></section>

<section className="section dark-section"><div className="container"><div className="section-head"><span className="eyebrow eyebrow-light">Por que IBESC?</span><h2>Mais do que um curso. Um caminho para o seu futuro.</h2><p>No IBESC, você encontra diferentes caminhos de formação em um só lugar.</p></div><div className="diff-grid">{[['01','Orientação para sua escolha','Você não precisa escolher sozinho. Nossa equipe ajuda você a encontrar a formação adequada aos seus objetivos.'],['02','Diversidade de formações','Graduação, pós-graduação e cursos técnicos em diferentes áreas.'],['03','Instituições parceiras','Opções de formação em parceria com instituições como UNINASSAU e UNIFAEL.'],['04','Atendimento próximo','Atendimento presencial em Boa Viagem e suporte durante sua jornada.']].map(d=><div className="card diff-card" key={d[0]}><span className="number">{d[0]}</span><h3>{d[1]}</h3><p>{d[2]}</p><CheckCircle2 size={18}/></div>)}</div></div></section>

<section className="section tech-section"><div className="container"><div className="section-head"><span className="eyebrow">Formação prática</span><h2>Quer entrar no mercado mais rápido?</h2><p>Conheça os cursos técnicos do IBESC e prepare-se para novas oportunidades profissionais.</p></div><div className="tech-grid"><article className="tech-card"><img src="/images/tecnico-enfermagem-1.png" alt="Técnico em Enfermagem - IBESC" loading="lazy"/><div><span className="tag">Curso Técnico · IBESC</span><h3>Técnico em Enfermagem</h3><p>Prepare-se para construir uma carreira na área da saúde com formação técnica e prática.</p><a className="btn btn-dark" href={waLink('Técnico em Enfermagem')}>Quero saber mais</a></div></article><article className="tech-card"><img src="/images/LOGO 2.jpeg" alt="Técnico em Informática - IBESC" loading="lazy"/><div><span className="tag">Curso Técnico · IBESC</span><h3>Técnico em Informática</h3><p>Desenvolva conhecimentos técnicos para atuar com tecnologia, suporte e informática.</p><a className="btn btn-dark" href={waLink('Técnico em Informática')}>Quero saber mais</a></div></article></div></div></section>

<section className="section partner-section"><div className="container"><div className="section-head centered"><span className="eyebrow">Instituições parceiras</span><h2>Grandes instituições. Novos caminhos para você.</h2><p>O IBESC atua na comercialização e orientação de cursos oferecidos em parceria com instituições de ensino.</p></div><div className="partner-grid"><div className="partner"><strong>UNINASSAU</strong><span>Instituição parceira</span></div><div className="partner"><strong>UNIFAEL</strong><span>Instituição parceira</span></div></div></div></section>

<section className="section"><div className="container"><div className="section-head centered"><span className="eyebrow">Como funciona</span><h2>Começar é mais simples do que você imagina</h2></div><div className="steps">{[['01','Escolha seu objetivo','Conte para nós o que você quer estudar.'],['02','Encontre seu curso','Nossa equipe apresenta as opções disponíveis para o seu perfil.'],['03','Faça sua matrícula','Receba orientação durante o processo de inscrição.'],['04','Comece sua formação','Agora é só dar o primeiro passo rumo ao seu próximo objetivo.']].map(s=><div className="card step-card" key={s[0]}><div className="step-num">{s[0]}</div><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></div></section>

<section className="section review-section"><div className="container review-grid"><div><span className="eyebrow">Avaliação Google</span><h2>Quem estuda com a gente, recomenda.</h2><p>Uma experiência educacional próxima, com estrutura e atendimento para acompanhar sua jornada.</p><div className="rating"><strong>5,0</strong><div><div className="stars">★★★★★</div><span>16 avaliações no Google</span></div></div></div><div className="testimonial"><div className="stars">★★★★★</div><p>“Muito satisfatório, estrutura ampla com laboratório e pessoas especializadas.”</p><hr/><p>“Excelente instituição de ensino.”</p><span className="link">Ver avaliações <ArrowRight size={15}/></span></div></div></section>

<section className="section location-section"><div className="container location-grid"><div className="location-copy"><span className="eyebrow">Boa Viagem — CE</span><h2>Um espaço para você começar seu próximo capítulo.</h2><p>Conheça nossa estrutura e conte com uma equipe preparada para acompanhar sua jornada.</p><div className="address"><MapPin size={20}/><div><strong>IBESC</strong><span>Rua David Capistrano, 802<br/>Várzea do Canto — Centro<br/>Boa Viagem — CE · 63870-000</span></div></div><a href="https://www.google.com/maps/search/?api=1&query=Rua+David+Capistrano+802+Boa+Viagem+CE" className="btn btn-dark">Como chegar <ArrowRight size={16}/></a></div><div className="location-photo"><img src="/images/tecnico-enfermagem-3.png" alt="Estrutura e formação prática do IBESC" loading="lazy"/></div></div></section>

<section className="section"><div className="container"><div className="cta"><div className="section-head"><span className="eyebrow">Atendimento personalizado</span><h2>Não sabe qual curso escolher?</h2><p>Fale com um de nossos consultores e descubra quais opções combinam com seus objetivos profissionais.</p></div><a href={waLink()} className="btn btn-dark">Falar com um consultor <MessageCircle size={17}/></a></div></div></section>

<section className="section final-cta"><div className="container"><div className="final-cta-inner"><span className="eyebrow eyebrow-light">Seu próximo passo</span><h2>O seu próximo passo pode começar hoje.</h2><p>Escolha sua formação, fale com nossa equipe e descubra as opções disponíveis para você.</p><div className="hero-actions"><Link href="/cursos" className="btn btn-primary">Encontre seu curso</Link><a href={waLink()} className="btn btn-outline">Falar no WhatsApp</a></div></div></div></section>
</main><Footer/><a className="whatsapp" href={waLink()} aria-label="Fale com um consultor no WhatsApp"><MessageCircle size={18}/> <span>Fale com um consultor</span></a></>}
