import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, MessageCircle, GraduationCap, Stethoscope, Building2, CheckCircle2, MapPin, Monitor } from 'lucide-react';
import { courses, categoryLabels, getCourseImage } from '@/data/courses';
import GoogleReviews from '@/components/GoogleReviews';
import { siteInfo } from '@/data/site';

const wa = '5588988498031';
const waLink = (course?: string) => `https://wa.me/${wa}?text=${encodeURIComponent(course ? `Olá! Vim pelo site do IBESC e gostaria de receber informações sobre o curso de ${course}.` : 'Olá! Vim pelo site do IBESC e gostaria de receber informações sobre os cursos.')}`;

const featuredCourseSlugs = ['tecnico-em-enfermagem', 'pedagogia', 'nutricao'];

export default function Home(){const featured=courses.filter(c=>featuredCourseSlugs.includes(c.slug) && c.status==='ATIVO').sort((a,b)=>featuredCourseSlugs.indexOf(a.slug)-featuredCourseSlugs.indexOf(b.slug)); const activeAreas=[...new Set(courses.filter(c=>c.status==='ATIVO').map(c=>c.area))].sort((a,b)=>a.localeCompare(b,'pt-BR')); return <><main>
<section className="hero home-hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow eyebrow-light"><MapPin size={14}/> IBESC · Boa Viagem — CE</span><h1>Formação para o seu futuro, <span>com grandes instituições ao seu lado.</span></h1><p>Escolha entre cursos próprios do IBESC e formações de instituições parceiras como UNINASSAU e UNIFAEL. Nossa equipe ajuda você a encontrar o melhor caminho.</p><div className="hero-actions"><Link href="/cursos" className="btn btn-primary">Encontrar meu curso <ArrowRight size={17}/></Link><a href={waLink()} className="btn btn-outline">Falar com um consultor</a></div><div className="hero-trust"><span>Graduação</span><i/> <span>Pós-graduação</span><i/> <span>Cursos Técnicos</span></div></div><div className="hero-visual hero-brand-panel"><div className="hero-brand-main"><span>Formação e atendimento</span><Image src="/images/LOGO OFICIAL.jpeg" alt="IBESC" width={700} height={350} priority sizes="(max-width: 800px) 78vw, 38vw"/></div><div className="hero-partners"><small>Instituições parceiras</small><div><Image src="/images/partners/uninassau.svg" alt="UNINASSAU" width={298} height={63}/><Image src="/images/partners/unifael.svg" alt="UNIFAEL" width={258} height={70}/></div></div></div></div></section>

<section className="institution-section"><div className="container"><div className="institution-intro"><span className="eyebrow">Escolha sua instituição</span><h2>Três caminhos, uma escolha mais simples.</h2><p>Compare as opções e vá direto para a formação que combina com o seu objetivo.</p></div><div className="institution-grid"><Link href="/cursos?institution=IBESC" className="institution-card institution-ibesc"><Image src="/images/LOGO OFICIAL.jpeg" alt="IBESC" width={400} height={140}/><div><strong>Formação própria</strong><p>Cursos técnicos e formação prática com atendimento próximo em Boa Viagem.</p><span>Ver cursos IBESC <ArrowRight size={15}/></span></div></Link><Link href="/cursos?institution=UNINASSAU" className="institution-card"><Image src="/images/partners/uninassau.svg" alt="UNINASSAU" width={298} height={63}/><div><strong>Instituição parceira</strong><p>Graduação e pós-graduação com orientação comercial do IBESC.</p><span>Ver cursos UNINASSAU <ArrowRight size={15}/></span></div></Link><Link href="/cursos?institution=UNIFAEL" className="institution-card"><Image src="/images/partners/unifael.svg" alt="UNIFAEL" width={258} height={70}/><div><strong>Instituição parceira</strong><p>Pós-graduação digital com apoio para encontrar a opção ideal.</p><span>Ver cursos UNIFAEL <ArrowRight size={15}/></span></div></Link></div></div></section>

<section className="section search-section home-search"><div className="container"><div className="section-head centered"><span className="eyebrow">Busca inteligente</span><h2>Qual curso você procura?</h2><p>Pesquise por nome ou combine área, formação e instituição.</p></div><form className="search-box" action="/cursos" method="get"><div className="search-grid"><input name="query" className="input" placeholder="Digite o nome do curso" aria-label="Nome do curso"/><select name="area" className="input" aria-label="Área"><option value="Todas">Área: Todas</option>{activeAreas.map(area=><option key={area} value={area}>{area}</option>)}</select><select name="category" className="input" aria-label="Formação"><option value="Todas">Formação: Todas</option>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select name="institution" className="input" aria-label="Instituição"><option value="Todas">Instituição: Todas</option><option value="IBESC">IBESC</option><option value="UNINASSAU">UNINASSAU</option><option value="UNIFAEL">UNIFAEL</option></select><button type="submit" className="btn btn-primary">Buscar <ArrowRight size={16}/></button></div></form></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Escolha seu caminho</span><h2>Qual caminho combina com você?</h2><p>Encontre a formação que faz sentido para o seu momento profissional.</p></div><div className="path-grid"><Link href="/cursos?category=GRADUACAO" className="card path-card"><div className="icon-wrap blue"><GraduationCap size={25}/></div><div><h3>Graduação</h3><p>Comece sua formação superior e construa uma carreira com novas possibilidades.</p></div><span className="link">Ver todas as graduações <ArrowRight size={15}/></span></Link><Link href="/cursos?category=POS_GRADUACAO" className="card path-card"><div className="icon-wrap green"><Building2 size={25}/></div><div><h3>Pós-graduação</h3><p>Especialize-se, atualize seus conhecimentos e avance profissionalmente.</p></div><span className="link">Ver todas as pós-graduações <ArrowRight size={15}/></span></Link><Link href="/cursos-tecnicos" className="card path-card"><div className="icon-wrap yellow"><Stethoscope size={25}/></div><div><h3>Cursos Técnicos</h3><p>Formação prática para quem quer se preparar para o mercado de trabalho.</p></div><span className="link">Ver todos os cursos técnicos <ArrowRight size={15}/></span></Link></div></div></section>

<section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Áreas de formação</span><h2>Explore nossas áreas</h2><p>Clique em uma área para visualizar apenas os cursos relacionados a ela.</p></div><div className="area-grid">{activeAreas.map(area=><Link href={`/cursos?area=${encodeURIComponent(area)}`} className="area-card" key={area}><span className="area-dot"/>{area}<small>Ver {courses.filter(c=>c.status==='ATIVO' && c.area===area).length} curso{courses.filter(c=>c.status==='ATIVO' && c.area===area).length === 1 ? '' : 's'} <ArrowRight size={13}/></small></Link>)}</div></div></section>

<section className="section featured-section"><div className="container"><div className="section-head row-head"><div><span className="eyebrow">Cursos em destaque</span><h2>Cursos que podem transformar sua carreira</h2></div><Link href="/cursos" className="link desktop-link">Ver todos os cursos <ArrowRight size={15}/></Link></div><div className="course-grid">{featured.map(c=><article className="card course-card" key={c.id}><div className="course-image image-real"><Image src={getCourseImage(c)} alt={c.name} width={600} height={400} sizes="(max-width: 800px) 50vw, 33vw"/></div><span className="tag">{c.type}</span><h3>{c.name}</h3><div className="course-meta">{Array.isArray(c.institution)?c.institution.join(' / '):c.institution} <span/> {c.area}</div><p>{c.description}</p><Link className="link" href={`/curso/${c.slug}`}>Saiba mais <ArrowRight size={15}/></Link></article>)}</div></div></section>

<section className="section dark-section"><div className="container"><div className="section-head"><span className="eyebrow eyebrow-light">Por que IBESC?</span><h2>Mais do que um curso. Um caminho para o seu futuro.</h2><p>No IBESC, você encontra diferentes caminhos de formação em um só lugar.</p></div><div className="diff-grid">{[['01','Orientação para sua escolha','Você não precisa escolher sozinho. Nossa equipe ajuda você a encontrar a formação adequada aos seus objetivos.'],['02','Diversidade de formações','Graduação, pós-graduação e cursos técnicos em diferentes áreas.'],['03','Instituições parceiras','Opções de formação em parceria com instituições como UNINASSAU e UNIFAEL.'],['04','Atendimento próximo','Atendimento presencial em Boa Viagem e suporte durante sua jornada.']].map(d=><div className="card diff-card" key={d[0]}><span className="number">{d[0]}</span><h3>{d[1]}</h3><p>{d[2]}</p><CheckCircle2 size={18}/></div>)}</div></div></section>

<section className="section tech-section"><div className="container"><div className="section-head"><span className="eyebrow">Formação prática</span><h2>Quer entrar no mercado mais rápido?</h2><p>Conheça os cursos técnicos do IBESC e prepare-se para novas oportunidades profissionais.</p></div><div className="tech-grid"><article className="tech-card"><Image src="/images/tecnico-enfermagem-1.webp" alt="Técnico em Enfermagem - IBESC" width={800} height={600} sizes="(max-width: 800px) 100vw, 50vw"/><div><span className="tag">Curso Técnico · IBESC</span><h3>Técnico em Enfermagem</h3><p>Prepare-se para construir uma carreira na área da saúde com formação técnica e prática.</p><a className="btn btn-dark" href={waLink('Técnico em Enfermagem')} data-conversion="whatsapp-tecnico-enfermagem">Quero saber mais</a></div></article><article className="tech-card"><div className="tech-visual tech-visual-computing" aria-hidden="true"><Monitor size={72}/></div><div><span className="tag">Curso Básico · IBESC</span><h3>Curso Básico de Informática</h3><p>Desenvolva conhecimentos técnicos para atuar com tecnologia, suporte e informática.</p><a className="btn btn-dark" href={waLink('Curso Básico de Informática')} data-conversion="whatsapp-informatica">Quero saber mais</a></div></article></div></div></section>

<section className="section partner-section"><div className="container"><div className="section-head centered"><span className="eyebrow">Instituições parceiras</span><h2>Grandes instituições. Novos caminhos para você.</h2><p>O IBESC atua na comercialização e orientação de cursos oferecidos em parceria com instituições de ensino.</p></div><div className="partner-grid"><a className="partner" href="https://www.uninassau.edu.br/" target="_blank" rel="noopener noreferrer" aria-label="Acessar o site oficial da UNINASSAU"><Image className="partner-logo" src="/images/partners/uninassau.svg" alt="UNINASSAU" width={298} height={63}/><span>Conheça o site oficial</span></a><a className="partner" href="https://posgrad.unifael.edu.br/digital?polo=boaviagemcentroii-ce&amp;tipo=digital" target="_blank" rel="noopener noreferrer" aria-label="Acessar a Pós-graduação Digital UNIFAEL do polo Boa Viagem"><Image className="partner-logo" src="/images/partners/unifael.svg" alt="UNIFAEL" width={258} height={70}/><span>Conheça a Pós-graduação Digital</span></a></div></div></section>

<section className="section"><div className="container"><div className="section-head centered"><span className="eyebrow">Como funciona</span><h2>Começar é mais simples do que você imagina</h2></div><div className="steps">{[['01','Escolha seu objetivo','Conte para nós o que você quer estudar.'],['02','Encontre seu curso','Nossa equipe apresenta as opções disponíveis para o seu perfil.'],['03','Faça sua matrícula','Receba orientação durante o processo de inscrição.'],['04','Comece sua formação','Agora é só dar o primeiro passo rumo ao seu próximo objetivo.']].map(s=><div className="card step-card" key={s[0]}><div className="step-num">{s[0]}</div><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></div></section>

<GoogleReviews />

<section className="section location-section"><div className="container location-grid"><div className="location-copy"><span className="eyebrow">Boa Viagem — CE</span><h2>Um espaço para você começar seu próximo capítulo.</h2><p>Conheça nossa estrutura e conte com uma equipe preparada para acompanhar sua jornada.</p><div className="address"><MapPin size={20}/><div><strong>IBESC</strong><span>Rua Deputado David Capistrano, 802<br/>Várzea do Canto<br/>Boa Viagem — CE · 63870-000</span></div></div><a href={siteInfo.googleMapsDirectionsUrl} target="_blank" rel="noopener noreferrer" className="btn btn-dark" data-conversion="google-como-chegar">Como chegar <ArrowRight size={16}/></a></div><div className="location-map"><iframe src={`https://www.google.com/maps?q=${encodeURIComponent(`${siteInfo.streetAddress}, ${siteInfo.neighborhood}, ${siteInfo.city} - ${siteInfo.state}, ${siteInfo.postalCode}`)}&z=17&output=embed`} title="Localização do IBESC no Google Maps" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a href={siteInfo.googleMapsDirectionsUrl} target="_blank" rel="noopener noreferrer" data-conversion="google-localizacao">Abrir no Google Maps <ArrowRight size={15}/></a></div></div></section>

<section className="section"><div className="container"><div className="cta"><div className="section-head"><span className="eyebrow">Atendimento personalizado</span><h2>Não sabe qual curso escolher?</h2><p>Fale com um de nossos consultores e descubra quais opções combinam com seus objetivos profissionais.</p></div><a href={waLink()} className="btn btn-dark">Falar com um consultor <MessageCircle size={17}/></a></div></div></section>

<section className="section final-cta"><div className="container"><div className="final-cta-inner"><span className="eyebrow eyebrow-light">Seu próximo passo</span><h2>O seu próximo passo pode começar hoje.</h2><p>Escolha sua formação, fale com nossa equipe e descubra as opções disponíveis para você.</p><div className="hero-actions"><Link href="/cursos" className="btn btn-primary">Encontre seu curso</Link><a href={waLink()} className="btn btn-outline">Falar no WhatsApp</a></div></div></div></section>
</main><a className="whatsapp" href={waLink()} aria-label="Fale com um consultor no WhatsApp"><MessageCircle size={18}/> <span>Fale com um consultor</span></a></>}

