import Link from 'next/link';
import { ExternalLink, MessageCircle, ArrowRight } from 'lucide-react';

export const metadata = { title: 'Pós-graduação | IBESC', description: 'Encontre sua pós-graduação com o IBESC e consulte os catálogos oficiais da UNINASSAU e UNIFAEL.' };
const uninassau = 'https://ead.uninassau.edu.br/pos-digital';
const unifael = 'https://posgrad.unifael.edu.br/digital?polo=boaviagemcentroii-ce&tipo=digital';
const whatsapp = 'https://wa.me/5588988498031?text=' + encodeURIComponent('Olá! Vim pelo site do IBESC e quero informações sobre pós-graduação.');

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Pós-graduação · UNINASSAU + UNIFAEL</span><h1>Sua graduação abriu uma porta. Sua especialização pode abrir muitas outras.</h1><p>Encontre uma pós-graduação para aprofundar seus conhecimentos e avançar profissionalmente.</p><div className="hero-actions"><a className="btn btn-primary" href={uninassau} target="_blank" rel="noopener noreferrer">Pós UNINASSAU <ExternalLink size={17}/></a><a className="btn btn-outline" href={unifael} target="_blank" rel="noopener noreferrer">Pós UNIFAEL <ExternalLink size={17}/></a></div></div></section><section className="section"><div className="container"><div className="section-head centered"><span className="eyebrow">Catálogos oficiais</span><h2>Escolha a instituição e explore as opções</h2><p>Os catálogos permanecem nas plataformas oficiais das instituições. O IBESC ajuda você a encontrar o caminho e oferece atendimento comercial em Boa Viagem.</p></div><div className="partner-grid"><div className="card"><span className="tag">Instituição parceira</span><h2>UNINASSAU</h2><p>Consulte o catálogo oficial de Pós-graduação Digital e veja as especializações disponíveis.</p><a className="btn btn-dark" href={uninassau} target="_blank" rel="noopener noreferrer">Ver catálogo UNINASSAU <ExternalLink size={16}/></a></div><div className="card"><span className="tag">Instituição parceira</span><h2>UNIFAEL</h2><p>Consulte o catálogo oficial de Pós-graduação Digital configurado para o polo de Boa Viagem.</p><a className="btn btn-dark" href={unifael} target="_blank" rel="noopener noreferrer">Ver catálogo UNIFAEL <ExternalLink size={16}/></a></div></div><div className="cta" style={{marginTop:40}}><h2>Não sabe qual pós escolher?</h2><p>Fale com um consultor do IBESC e receba orientação sobre as opções disponíveis.</p><a href={whatsapp} className="btn btn-dark">Falar no WhatsApp <MessageCircle size={17}/></a></div></div></section><div className="container" style={{paddingBottom:70}}><Link href="/" className="link">← Voltar para o início <ArrowRight size={15}/></Link></div></main>;
}