import Link from 'next/link';
import Image from 'next/image';
import { ExternalLink, MessageCircle, ArrowRight, GraduationCap, Search, BadgeCheck } from 'lucide-react';

export const metadata = { title: 'Pós-graduação UNINASSAU e UNIFAEL | IBESC', description: 'Compare os caminhos de pós-graduação e consulte os catálogos oficiais da UNINASSAU e UNIFAEL com orientação do IBESC.' };
const uninassau = 'https://ead.uninassau.edu.br/pos-digital';
const unifael = 'https://posgrad.unifael.edu.br/digital?polo=boaviagemcentroii-ce&tipo=digital';
const whatsapp = 'https://wa.me/5588988498031?text=' + encodeURIComponent('Olá! Vim pelo site do IBESC e quero orientação sobre pós-graduação.');

export default function Page() {
  return <main><section className="hero"><div className="container"><span className="eyebrow eyebrow-light">Pós-graduação · instituições parceiras</span><h1>Compare opções e consulte a fonte oficial</h1><p>Explore especializações da UNINASSAU e da UNIFAEL. O IBESC oferece suporte acadêmico e atendimento para ajudar você a organizar sua escolha.</p><div className="hero-actions"><a className="btn btn-primary" href="#instituicoes">Comparar instituições <ArrowRight size={17}/></a><a className="btn btn-outline" href={whatsapp}>Falar com o IBESC <MessageCircle size={17}/></a></div></div></section>
  <section className="section" id="instituicoes"><div className="container"><div className="section-head centered"><span className="eyebrow">Catálogos oficiais</span><h2>Escolha onde deseja pesquisar</h2><p>A oferta, a matriz curricular, a duração e as regras acadêmicas devem ser confirmadas diretamente na plataforma oficial da instituição responsável.</p></div><div className="partner-grid"><article className="card institution-choice theme-uninassau"><Image src="/images/partners/uninassau.svg" alt="UNINASSAU" width={298} height={63}/><span className="tag">Instituição responsável</span><h2>Pós-graduação Digital UNINASSAU</h2><p>Consulte as especializações e as informações atuais no catálogo oficial.</p><a className="btn btn-dark" href={uninassau} target="_blank" rel="noopener noreferrer">Ver catálogo UNINASSAU <ExternalLink size={16}/></a></article><article className="card institution-choice theme-unifael"><Image src="/images/partners/unifael.svg" alt="UNIFAEL" width={258} height={70}/><span className="tag">Instituição responsável</span><h2>Pós-graduação Digital UNIFAEL</h2><p>Consulte o catálogo oficial configurado para o atendimento relacionado a Boa Viagem.</p><a className="btn btn-dark" href={unifael} target="_blank" rel="noopener noreferrer">Ver catálogo UNIFAEL <ExternalLink size={16}/></a></article></div></div></section>
  <section className="section" style={{background:'var(--light)'}}><div className="container"><div className="section-head"><span className="eyebrow">Antes de escolher</span><h2>Três pontos para confirmar</h2></div><div className="path-grid"><div className="card"><GraduationCap/><h3>Requisito de ingresso</h3><p>A pós-graduação é destinada a pessoas que atendem aos requisitos de formação definidos pela instituição responsável.</p></div><div className="card"><Search/><h3>Oferta atual</h3><p>Confirme modalidade, duração, matriz e disponibilidade no catálogo oficial.</p></div><div className="card"><BadgeCheck/><h3>Responsabilidade institucional</h3><p>A instituição escolhida responde pela formação. O IBESC atua no suporte acadêmico e atendimento.</p></div></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Dúvidas frequentes</span><h2>Entenda o processo</h2></div><div className="faq-list"><details><summary>Quem oferece o suporte acadêmico?</summary><p>O suporte acadêmico de todos os cursos é realizado pela equipe do IBESC.</p></details><details><summary>Quem responde pela oferta e certificação?</summary><p>A UNINASSAU ou a UNIFAEL, conforme a formação escolhida, responde pela oferta, pelas regras acadêmicas e pela certificação.</p></details><details><summary>As informações podem mudar?</summary><p>Sim. Catálogo, disponibilidade e condições podem ser atualizados pelas instituições. Por isso, a confirmação final deve ocorrer na fonte oficial.</p></details><details><summary>Como escolher entre as instituições?</summary><p>Compare a oferta disponível, a área pretendida e as informações acadêmicas de cada catálogo. A equipe IBESC pode ajudar a organizar essa pesquisa.</p></details></div><div className="cta" style={{marginTop:40}}><div><h2>Precisa de orientação?</h2><p>Informe sua área de interesse e converse com a equipe do IBESC.</p></div><a href={whatsapp} className="btn btn-dark">Falar no WhatsApp <MessageCircle size={17}/></a></div></div></section><div className="container" style={{paddingBottom:70}}><Link href="/cursos" className="link">Ver catálogo do site <ArrowRight size={15}/></Link></div></main>;
}
